{
  "openapi": "3.0.1",
  "info": {
    "title": "CRS Conversion Service",
    "description": "Provides conversion/transformation services from a source to a target CRS. A coordinate operation is a conversion if the source and target CRS share the same datum; the operation is called transformation if datum transformations are involved, i.e. source and target CRS do not share the same datum.",
    "contact": {
      "name": "OSDU Data Platform Team",
      "email": "dps@OSDU.org"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "4.0.0"
  },
  "host": "az-osdu1.evd.csp.slb.com",
  "x-google-allow": "all",
  "basePath": "/api/crs/v1",
  "security": [
    {
      "Bearer": []
    },
    {
      "google_id_token": []
    }
  ],
  "tags": [
    {
      "name": "info-api",
"description": "Version info endpoint"
    },
    {
    
    "name": "Trajectory Computation and Conversion (v4) (EXPERIMENTAL)"
      "description": "Convert trajectory stations"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/v4/convertTrajectory": {
      "post": {
        "tags": [
          "Trajectory Computation and Conversion (v4) (EXPERIMENTAL)"
        ],
        "operationId": "convertTrajectory",
        "parameters": [
		{
            "in": "body",
            "name": "body",
            "required": false,
            "schema": {
              "$ref": "#/definitions/ConvertTrajectoryRequestV4"
            }
          },
          {
            "name": "data-partition-id",
            "in": "header",
            "description": "Tenant Id",
            "required": false
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/definitions/ConvertTrajectoryRequestV4"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
                "schema": {
                  "$ref": "#/definitions/ConvertTrajectoryResponseV4"
                }
          },
		 "400": {
            "description": "Bad input format",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
		 "503": {
            "description": "CRS-converter overloaded; try again later. See HttpHeader 'Retry-After'.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
	"/v4/info": {
      "get": {
          "tags": [
              "Info Api"
          ],
          "summary": "info",
          "operationId": "infoUsingGET",
          "consumes": [
              "application/json"
          ],
          "produces": [
              "application/json"
          ],
          "parameters": [
              {
                  "name": "data-partition-id",
                  "in": "header",
                  "description": "tenant",
                  "required": true,
                  "type": "string",
                  "default": "opendes"
              }
          ],
          "responses": {
              "200": {
                  "description": "OK",
                  "schema": {
                      "$ref": "#/definitions/VersionInfo"
                  }
              },
              "401": {
                  "description": "Unauthorized"
              },
              "403": {
                  "description": "Forbidden"
              },
              "404": {
                  "description": "Not Found"
              }
          }
      }
  }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "definitions": {
    "Point": {
      "type": "object",
      "required": [
        "x",
        "y",
        "z"
      ],
      "properties": {
        "x": {
          "type": "number",
          "format": "double",
          "example": 484074.5862320617,
          "description": "x coordinate or longitude"
        },
        "y": {
          "type": "number",
          "format": "double",
          "example": 5499819.191561815,
          "description": "y coordinate or latitude"
        },
        "z": {
          "type": "number",
          "format": "double",
          "example": 0,
          "description": "z coordinate"
        }
      },
      "description": "Point representation for CRS operations"
    },
    "TrajectoryStationOut": {
      "type": "object",
      "required": [
        "azimuthGN",
        "azimuthTN",
        "dxTN",
        "dyTN",
        "inclination",
        "md",
        "point"
      ],
      "properties": {
        "md": {
          "type": "number",
          "format": "double",
          "example": 2563.56,
          "description": "MD (measured depth) from vertical reference point in 'unitZ'."
        },
        "inclination": {
          "type": "number",
          "format": "double",
          "example": 15,
          "description": "Inclination angle in degrees of arc, 0.0 is vertical, 90.0 is horizontal."
        },
        "azimuthTN": {
          "type": "number",
          "format": "double",
          "example": 355.96,
          "description": "True North azimuth angle in degrees of arc, 0.0/360.0 is North."
        },
        "azimuthGN": {
          "type": "number",
          "format": "double",
          "example": 355,
          "description": "Grid North azimuth angle in degrees of arc, 0.0/360.0 is North."
        },
        "dxTN": {
          "type": "number",
          "format": "double",
          "example": 55.9,
          "description": "True E-W deviation in the local Cartesian engineering CRS from the well reference point; unit is given by container's 'unitXY'."
        },
        "dyTN": {
          "type": "number",
          "format": "double",
          "example": -145.3,
          "description": "True N-S deviation in the local Cartesian engineering CRS from the well reference point; Y is aligned with TrueNorth; unit is given by container's 'unitXY'."
        },
        "point": {
          "description": "Trajectory station point in trajectoryCRS and vertical unit as defined in container's 'unitZ'.",
          "$ref": "#/definitions/Point"
        },
        "wgs84Longitude": {
          "type": "number",
          "format": "double",
          "description": "WGS 84 longitude in dega"
        },
        "wgs84Latitude": {
          "type": "number",
          "format": "double",
          "description": "WGS 84 latitude in dega"
        },
        "dls": {
          "type": "number",
          "format": "double",
          "description": "Curvature, Dog Leg Severity, measured in 'unitDls'."
        },
        "original": {
          "type": "boolean",
          "description": "Original trajectory station if true, interpolated trajectory station if false."
        },
        "dz": {
          "type": "number",
          "format": "double"
        }
      },
      "description": "Output trajectory station record; context is provided by the container."
    },
    "ErrorResponse": {
      "type": "object",
      "properties": {
        "error": {
          "type": "string",
          "description": "Error message"
        }
      },
      "description": "Response resulting of a failed CRS convertion operation"
    },
    "ConvertTrajectoryRequest": {
      "type": "object",
      "required": [
        "azimuthReference",
        "inputStations",
        "method",
        "referencePoint",
        "trajectoryCRS",
        "unitZ"
      ],
      "properties": {
        "trajectoryCRS": {
          "type": "string",
          "example": "osdu:reference-data--CoordinateReferenceSystem:BoundProjected:EPSG::23032_EPSG::1612:",
          "description": "Coordinate reference system for the reference point; typically the CRS is a projected CRS; if a geographic CRS is provided, the unitXY must be defined and the azimuthReference must be TrueNorth. The property value could be a persistable reference string or a record ID"
        },
        "azimuthReference": {
          "type": "string",
          "example": "TrueNorth",
          "description": "Azimuth reference for the input trajectory station azimuth values (TrueNorth or GridNorth)"
        },
        "unitXY": {
          "type": "string",
          "example": "osdu:reference-data--UnitOfMeasure:m:",
          "description": "The horizontal unit of the dx, dy in the input trajectory stations; the unit must be a length unit in persistable reference or a record ID, see example."
        },
        "unitZ": {
          "type": "string",
          "example": "osdu:reference-data--UnitOfMeasure:m:",
          "description": "The vertical unit of the dz in the input trajectory stations; the unit could be a persistable reference or a record ID"
        },
        "referencePoint": {
          "description": "The 3D reference point in the 'trajectoryCRS' where MD==0.",
          "$ref": "#/definitions/Point"
        },
        "inputStations": {
          "type": "array",
          "description": "The array of input trajectory stations",
          "items": {
            "$ref": "#/definitions/TrajectoryStationIn"
          }
        },
        "method": {
          "type": "string",
          "example": "AzimuthalEquidistant",
          "description": "The computation method - 'AzimuthalEquidistant' (default) or 'LMP' (Lee's modified proposal SPE96813)"
        },
        "inputKind": {
          "type": "string",
          "example": "MD_Incl_Azim",
          "description": "The kind of input; one of MD_Incl_Azim (default), MD_X_Y_Z, MD_dX_dY_dZ, X_Y_Z, dX_dY_dZ. MD stands for measured depth; MD_X_Y_Z/X_Y_Z stand for absolute coordinates in the reference CRS, MD_dX_dY_dZ/dX_dY_dZ stand for deviations relative to the reference point."
        },
        "interpolate": {
          "type": "boolean",
          "description": "Perform trajectory interpolation on demand; default is true."
        }
      },
      "description": "Input trajectory data structure; contains the context (crs, units, azimuth reference, method)",
      "example": {
        "azimuthReference": "GN",
        "interpolate": false,
        "referencePoint": {
          "y": 6500000,
          "x": 400000,
          "z": 0
        },
        "unitZ": "osdu:reference-data--UnitOfMeasure:m:",
        "inputStations": [
          {
            "md": 0,
            "azimuth": 20,
            "inclination": 0
          },
          {
            "md": 100,
            "azimuth": 40,
            "inclination": 10
          },
          {
            "md": 150,
            "azimuth": 60,
            "inclination": 20
          },
          {
            "md": 200,
            "azimuth": 80,
            "inclination": 40
          }
        ],
        "trajectoryCRS": "osdu:reference-data--CoordinateReferenceSystem:Projected:EPSG::32631:",
        "inputKind": "MD_Incl_Azim",
        "MD_i": {
          "md_i": [
            50,
            125,
            175
          ]
        },
        "method": "AzimuthalEquidistant"
      }
    },
    "TrajectoryStationIn": {
      "type": "object",
      "required": [
        "azimuth",
        "inclination",
        "md"
      ],
      "properties": {
        "md": {
          "type": "number",
          "format": "double",
          "example": 1000,
          "description": "MD (measured depth) from vertical reference point in 'unitZ'."
        },
        "inclination": {
          "type": "number",
          "format": "double",
          "example": 10,
          "description": "Inclination angle in degrees of arc, 0.0 is vertical, 90.0 is horizontal."
        },
        "azimuth": {
          "type": "number",
          "format": "double",
          "example": 100,
          "description": "Azimuth angle in degrees of arc, 0.0/360.0 is North; reference given by azimuthReference (TrueNorth or GridNorth)."
        },
        "dx": {
          "type": "number",
          "format": "double",
          "example": 55.9,
          "description": "E-W deviation in the local Cartesian engineering CRS from the well reference point; unit is given by container's 'unitXY' or projected 'trajectoryCRS'."
        },
        "dy": {
          "type": "number",
          "format": "double",
          "example": -145.3,
          "description": "N-S deviation in the local Cartesian engineering CRS from the well reference point; Y is aligned with azimuth reference (TrueNorth or projected GridNorth); unit is given by container's 'unitXY' or projected 'trajectoryCRS'."
        },
        "dz": {
          "type": "number",
          "format": "double",
          "example": 1965.6,
          "description": "True vertical deviation in the local Cartesian engineering CRS from the well reference point; unit is given by container's unitZ; downwards positive."
        }
      },
      "description": "Input trajectory station record; context is provided by the container."
    },
    "ConvertTrajectoryRequestV4": {
      "required": [
        "inputStations",
        "method",
        "trajectoryCRS",
        "unitZ"
      ],
      "type": "object",
      "properties": {
        "trajectoryCRS": {
            "type": "string",
            "description": "Coordinate reference system for the reference point; typically the CRS is a projected CRS; if a geographic CRS is provided, the unitXY must be defined and the azimuthReference must be TRUE_NORTH.",
            "example": "\"{\"wkt\":\"PROJCS[\\\"WGS_1984_UTM_Zone_31N\\\",GEOGCS[\\\"GCS_WGS_1984\\\",DATUM[\\\"D_WGS_1984\\\",SPHEROID[\\\"WGS_1984\\\",6378137.0,298.257223563]],PRIMEM[\\\"Greenwich\\\",0.0],UNIT[\\\"Degree\\\",0.0174532925199433]],PROJECTION[\\\"Transverse_Mercator\\\"],PARAMETER[\\\"False_Easting\\\",500000.0],PARAMETER[\\\"False_Northing\\\",0.0],PARAMETER[\\\"Central_Meridian\\\",3.0],PARAMETER[\\\"Scale_Factor\\\",0.9996],PARAMETER[\\\"Latitude_Of_Origin\\\",0.0],UNIT[\\\"Meter\\\",1.0],AUTHORITY[\\\"EPSG\\\",32631]]\",\"ver\":\"PE_10_3_1\",\"name\":\"WGS_1984_UTM_Zone_31N\",\"authCode\":{\"auth\":\"EPSG\",\"code\":\"32631\"},\"type\":\"LBC\"}\""
        },
        "azimuthReference": {
            "type": "string",
            "description": "azimuth reference for the input trajectory station azimuth values (TRUE_NORTH or GridNorth)",
            "example": "TRUE_NORTH"
        },
        "unitXY": {
            "type": "string",
            "description": "The horizontal unit of the dx, dy in the input trajectory stations; the unit must be a length unit in 'persistable model' format, see example.",
            "example": "\"{\"scaleOffset\":{\"scale\":1.0,\"offset\":0.0},\"symbol\":\"m\",\"baseMeasurement\":{\"ancestry\":\"Length\",\"type\":\"UM\"},\"type\":\"USO\"}\""
        },
        "unitZ": {
            "type": "string",
            "description": "The vertical unit of the dz in the input trajectory stations; the unit must be a length unit in 'persistable model' format, see example.",
            "example": "\"{\"scaleOffset\":{\"scale\":1.0,\"offset\":0.0},\"symbol\":\"m\",\"baseMeasurement\":{\"ancestry\":\"Length\",\"type\":\"UM\"},\"type\":\"USO\"}\""
        },
        "referencePoint": {
          "$ref": "#/definitions/Point"
        },
        "inputStations": {
          "type": "array",
            "description": "The array of input trajectory stations",
            "example": [
              {
                "md": 0,
                "inclination": 0,
                "azimuth": 0
              },
              {
                "md": 1000,
                "inclination": 0,
                "azimuth": 0
              },
              {
                "md": 2000,
                "inclination": 90,
                "azimuth": 0
              },
              {
                "md": 3000,
                "inclination": 90,
                "azimuth": 0
              },
              {
                "md": 5000,
                "inclination": 90,
                "azimuth": 90
              },
              {
                "md": 6000,
                "inclination": 90,
                "azimuth": 90
              }
            ],
          "items": {
            "$ref": "#/definitions/TrajectoryStationInV4"
          }
        },
        "method": {
            "type": "string",
            "description": "The computation method - 'AzimuthalEquidistant' (default) or 'LMP' (Lee's modified proposal SPE96813)",
            "example": "AzimuthalEquidistant"
        },
        "inputKind": {
            "type": "string",
            "description": "The kind of input; one of MD_Inclination_Azimuth (default), MD_X_Y_Z, MD_dX_dY_dZ, X_Y_Z, dX_dY_dZ. MD stands for measured depth; MD_X_Y_Z/X_Y_Z stand for absolute coordinates in the reference CRS, MD_dX_dY_dZ/dX_dY_dZ stand for deviations relative to the reference point.",
            "example": "MD_Inclination_Azimuth"
        },
        "interpolate": {
            "type": "boolean",
            "description": "Perform trajectory interpolation on demand; default is true.",
            "example": true
        },
        "MD_i": {
          "$ref": "#/definitions/MinimumDepthInterval"
          },
          "unitMD": {
            "type": "string"
          }
      }
    },
	"example":{
    "azimuthReference": "GN",
    "interpolate": false,
    "referencePoint": {
        "x": 400000,
        "y": 6500000,
        "z": 100
    },
    "unitZ": "osdu:reference-data--UnitOfMeasure:m:",
    "unitMD": "osdu:reference-data--UnitOfMeasure:m:",
    "inputStations": [
        {
            "md": 0,
            "inclination": 0,
            "azimuth": 20
        },
        {
            "md": 100,
            "inclination": 10,
            "azimuth": 40
        }
    ],
    "MD_i": {
        "md_i": [
            50,
            75
        ]
    },
    "trajectoryCRS": "osdu:reference-data--CoordinateReferenceSystem:Projected:EPSG::32631:",
    "inputKind": "MD_Incl_Azim",
    "method": "AzimuthalEquidistant"
},
    "MinimumDepthInterval": {
      "type": "object",
      "properties": {
        "md_i": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "double"
          }
        },
        "md_interval": {
          "type": "number",
          "format": "double"
        }
      }
    },
      "TrajectoryStationInV4": {
        "required": [
          "inclination",
          "md"
        ],
        "type": "object",
        "properties": {
          "md": {
            "type": "number",
            "description": "MD (measured depth) from vertical reference point in 'unitZ'.",
            "format": "double",
            "example": 2563.56
          },
          "inclination": {
            "type": "number",
            "description": "Inclination angle in degrees of arc, 0.0 is vertical, 90.0 is horizontal.",
            "format": "double",
            "example": 15.0
          },
          "azimuth": {
            "type": "number",
            "description": "Azimuth angle in degrees of arc, 0.0/360.0 is North; reference given by azimuthReference (TRUE_NORTH or GridNorth).",
            "format": "double",
            "example": 355.0
          },
          "dx": {
            "type": "number",
            "description": "E-W deviation in the local Cartesian engineering CRS from the well reference point; unit is given by container's 'unitXY' or projected 'trajectoryCRS'.",
            "format": "double",
            "example": 55.9
          },
          "dy": {
            "type": "number",
            "description": "N-S deviation in the local Cartesian engineering CRS from the well reference point; Y is aligned with azimuth reference (TRUE_NORTH or projected GridNorth); unit is given by container's 'unitXY' or projected 'trajectoryCRS'.",
            "format": "double",
            "example": -145.3
          },
          "dz": {
            "type": "number",
            "description": "True vertical deviation in the local Cartesian engineering CRS from the well reference point; unit is given by container's unitZ; downwards positive.",
            "format": "double",
            "example": 1965.6
          }
        },
        "description": "Input trajectory station record; context is provided by the container.",
        "example": [
          {
            "md": 0,
            "inclination": 0,
            "azimuth": 0
          },
          {
            "md": 1000,
            "inclination": 0,
            "azimuth": 0
          },
          {
            "md": 2000,
            "inclination": 90,
            "azimuth": 0
          },
          {
            "md": 3000,
            "inclination": 90,
            "azimuth": 0
          },
          {
            "md": 5000,
            "inclination": 90,
            "azimuth": 90
          },
          {
            "md": 6000,
            "inclination": 90,
            "azimuth": 90
          }
        ]
      },
    "ConvertTrajectoryResponseV4": {
      "required": [
        "localCRS",
        "method",
        "stations",
        "trajectoryCRS",
        "unitDls",
        "unitXY",
        "unitZ"
      ],
      "type": "object",
      "properties": {
        "trajectoryCRS": {
            "type": "string",
            "description": "Coordinate reference system for the reference point; typically the CRS is a projected CRS; if a geographic CRS is provided, the unitXY must be defined and the azimuthReference must be TRUE_NORTH.",
            "example": "{\"authCode\":{\"auth\":\"SLB\",\"code\":\"30200002\"},\"lateBoundCRS\":{\"authCode\":{\"auth\":\"EPSG\",\"code\":\"30200\"},\"name\":\"Trinidad_1903_Trinidad_Grid\",\"type\":\"LBC\",\"ver\":\"PE_10_3_1\",\"wkt\":\"PROJCS[\\\"Trinidad_1903_Trinidad_Grid\\\",GEOGCS[\\\"GCS_Trinidad_1903\\\",DATUM[\\\"D_Trinidad_1903\\\",SPHEROID[\\\"Clarke_1858\\\",6378293.64520876,294.260676369]],PRIMEM[\\\"Greenwich\\\",0.0],UNIT[\\\"Degree\\\",0.0174532925199433]],PROJECTION[\\\"Cassini\\\"],PARAMETER[\\\"False_Easting\\\",430000.0],PARAMETER[\\\"False_Northing\\\",325000.0],PARAMETER[\\\"Central_Meridian\\\",-61.3333333333333],PARAMETER[\\\"Scale_Factor\\\",1.0],PARAMETER[\\\"Latitude_Of_Origin\\\",10.4416666666667],UNIT[\\\"Link_Clarke\\\",0.201166195164],AUTHORITY[\\\"EPSG\\\",30200]]\"},\"name\":\"Trinidad 1903 * EOG-Tto Trin / Trinidad Grid [30200,10085]\",\"singleCT\":{\"authCode\":{\"auth\":\"EPSG\",\"code\":\"10085\"},\"name\":\"Trinidad_1903_To_WGS_1984_2\",\"type\":\"ST\",\"ver\":\"PE_10_3_1\",\"wkt\":\"GEOGTRAN[\\\"Trinidad_1903_To_WGS_1984_2\\\",GEOGCS[\\\"GCS_Trinidad_1903\\\",DATUM[\\\"D_Trinidad_1903\\\",SPHEROID[\\\"Clarke_1858\\\",6378293.64520876,294.260676369]],PRIMEM[\\\"Greenwich\\\",0.0],UNIT[\\\"Degree\\\",0.0174532925199433]],GEOGCS[\\\"GCS_WGS_1984\\\",DATUM[\\\"D_WGS_1984\\\",SPHEROID[\\\"WGS_1984\\\",6378137.0,298.257223563]],PRIMEM[\\\"Greenwich\\\",0.0],UNIT[\\\"Degree\\\",0.0174532925199433]],METHOD[\\\"Geocentric_Translation\\\"],PARAMETER[\\\"X_Axis_Translation\\\",-61.0],PARAMETER[\\\"Y_Axis_Translation\\\",285.2],PARAMETER[\\\"Z_Axis_Translation\\\",471.6],AUTHORITY[\\\"EPSG\\\",10085]]\"},\"type\":\"EBC\",\"ver\":\"PE_10_3_1\"}"
        },
        "unitXY": {
            "type": "string",
            "description": "The horizontal unit of the dx, dy in the output trajectory stations.",
            "example": "{\"scaleOffset\":{\"scale\":1.0,\"offset\":0.0},\"symbol\":\"m\",\"baseMeasurement\":{\"ancestry\":\"Length\",\"type\":\"UM\"},\"type\":\"USO\"}"
        },
        "unitZ": {
            "type": "string",
            "description": "The vertical unit of the dz in the output trajectory stations.",
            "example": "{\"scaleOffset\":{\"scale\":1.0,\"offset\":0.0},\"symbol\":\"m\",\"baseMeasurement\":{\"ancestry\":\"Length\",\"type\":\"UM\"},\"type\":\"USO\"}"
        },
        "unitDls": {
            "type": "string",
            "description": "The unit of the dog leg severity (DLS) in the output trajectory stations.",
            "example": "%7B%22ScaleOffset%22%3A%7B%22Scale%22%3A5.72614583987641E-4%2C%22Offset%22%3A0.0%7D%2C%22Symbol%22%3A%22deg%2F100ft%22%2C%22BaseMeasurement%22%3A%22%257B%2522Ancestry%2522%253A%2522Rotation_Per_Length%2522%257D%22%7D"
        },
        "stations": {
          "type": "array",
            "description": "Computed trajectory stations.",
          "items": {
            "$ref": "#/definitions/TrajectoryStationOut"
          }
        },
        "localCRS": {
            "type": "string",
            "description": "Coordinate Reference System for the local, True North oriented, true distance, engineering CRS with origin at the well's surface location.",
            "example": "{\"authCode\":{\"auth\":\"SLB\",\"code\":\"30200002\"},\"lateBoundCRS\":{\"authCode\":{\"auth\":\"EPSG\",\"code\":\"30200\"},\"name\":\"Trinidad_1903_Trinidad_Grid\",\"type\":\"LBC\",\"ver\":\"PE_10_3_1\",\"wkt\":\"PROJCS[\\\"Trinidad_1903_Trinidad_Grid\\\",GEOGCS[\\\"GCS_Trinidad_1903\\\",DATUM[\\\"D_Trinidad_1903\\\",SPHEROID[\\\"Clarke_1858\\\",6378293.64520876,294.260676369]],PRIMEM[\\\"Greenwich\\\",0.0],UNIT[\\\"Degree\\\",0.0174532925199433]],PROJECTION[\\\"Cassini\\\"],PARAMETER[\\\"False_Easting\\\",430000.0],PARAMETER[\\\"False_Northing\\\",325000.0],PARAMETER[\\\"Central_Meridian\\\",-61.3333333333333],PARAMETER[\\\"Scale_Factor\\\",1.0],PARAMETER[\\\"Latitude_Of_Origin\\\",10.4416666666667],UNIT[\\\"Link_Clarke\\\",0.201166195164],AUTHORITY[\\\"EPSG\\\",30200]]\"},\"name\":\"Trinidad 1903 * EOG-Tto Trin / Trinidad Grid [30200,10085]\",\"singleCT\":{\"authCode\":{\"auth\":\"EPSG\",\"code\":\"10085\"},\"name\":\"Trinidad_1903_To_WGS_1984_2\",\"type\":\"ST\",\"ver\":\"PE_10_3_1\",\"wkt\":\"GEOGTRAN[\\\"Trinidad_1903_To_WGS_1984_2\\\",GEOGCS[\\\"GCS_Trinidad_1903\\\",DATUM[\\\"D_Trinidad_1903\\\",SPHEROID[\\\"Clarke_1858\\\",6378293.64520876,294.260676369]],PRIMEM[\\\"Greenwich\\\",0.0],UNIT[\\\"Degree\\\",0.0174532925199433]],GEOGCS[\\\"GCS_WGS_1984\\\",DATUM[\\\"D_WGS_1984\\\",SPHEROID[\\\"WGS_1984\\\",6378137.0,298.257223563]],PRIMEM[\\\"Greenwich\\\",0.0],UNIT[\\\"Degree\\\",0.0174532925199433]],METHOD[\\\"Geocentric_Translation\\\"],PARAMETER[\\\"X_Axis_Translation\\\",-61.0],PARAMETER[\\\"Y_Axis_Translation\\\",285.2],PARAMETER[\\\"Z_Axis_Translation\\\",471.6],AUTHORITY[\\\"EPSG\\\",10085]]\"},\"type\":\"EBC\",\"ver\":\"PE_10_3_1\"}"
        },
        "method": {
            "type": "string",
            "description": "The computation method used - 'AzimuthalEquidistant' (default) or 'LMP' (Lee's modified proposal SPE96813).",
            "example": "AzimuthalEquidistant"
        },
        "operationsApplied": {
          "type": "array",
            "description": "The list of operations performed on the points as a list of strings",
          "items": {
              "type": "string",
              "description": "The list of operations performed on the points as a list of strings"
          }
        },
        "stations_i": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/TrajectoryStationOut"
          }
        },
        "scaleConvergenceList": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ScaleConvergence"
          }
        },
          "unitMD": {
            "type": "string"
          },
        "inputKind": {
            "type": "string",
            "description": "The kind of input; one of MD_Inclination_Azimuth (default), MD_X_Y_Z, MD_dX_dY_dZ, X_Y_Z, dX_dY_dZ. MD stands for measured depth; MD_X_Y_Z/X_Y_Z stand for absolute coordinates in the reference CRS, MD_dX_dY_dZ/dX_dY_dZ stand for deviations relative to the reference point.",
            "example": "MD_Inclination_Azimuth"
        }
      }
    },
	"example":{
    "trajectoryCRS": "{\"authCode\":{\"auth\":\"EPSG\",\"code\":\"32631\"},\"name\":\"WGS_1984_UTM_Zone_31N\",\"type\":\"LBC\",\"ver\":\"PE_10_9_1\",\"wkt\":\"PROJCS[\\\"WGS_1984_UTM_Zone_31N\\\",GEOGCS[\\\"GCS_WGS_1984\\\",DATUM[\\\"D_WGS_1984\\\",SPHEROID[\\\"WGS_1984\\\",6378137.0,298.257223563]],PRIMEM[\\\"Greenwich\\\",0.0],UNIT[\\\"Degree\\\",0.0174532925199433]],PROJECTION[\\\"Transverse_Mercator\\\"],PARAMETER[\\\"False_Easting\\\",500000.0],PARAMETER[\\\"False_Northing\\\",0.0],PARAMETER[\\\"Central_Meridian\\\",3.0],PARAMETER[\\\"Scale_Factor\\\",0.9996],PARAMETER[\\\"Latitude_Of_Origin\\\",0.0],UNIT[\\\"Meter\\\",1.0],AUTHORITY[\\\"EPSG\\\",32631]]\"}",
    "unitXY": "{\"abcd\":{\"a\":0.0,\"b\":1.0,\"c\":1.0,\"d\":0.0},\"symbol\":\"m\",\"baseMeasurement\":{\"ancestry\":\"L\",\"type\":\"UM\"},\"type\":\"UAD\"}",
    "unitZ": "{\"abcd\":{\"a\":0.0,\"b\":1.0,\"c\":1.0,\"d\":0.0},\"symbol\":\"m\",\"baseMeasurement\":{\"ancestry\":\"L\",\"type\":\"UM\"},\"type\":\"UAD\"}",
    "unitDls": "{\"scaleOffset\":{\"scale\":5.72614583987641E-4,\"offset\":0.0},\"symbol\":\"deg/100ft\",\"baseMeasurement\":{\"ancestry\":\"Rotation_Per_Length\",\"type\":\"UM\"},\"type\":\"USO\"}",
    "stations": [
        {
            "md": 0.0,
            "inclination": 0.0,
            "azimuthTN": 18.529449533844627,
            "azimuthGN": 20.0,
            "dxTN": 0.0,
            "dyTN": 0.0,
            "point": {
                "x": 399999.99999999936,
                "y": 6499999.999999927,
                "z": 100.0
            },
            "wgs84Longitude": 1.2778067531835464,
            "wgs84Latitude": 58.62877104865894,
            "dls": 0.0,
            "original": true,
            "dz": 0.0
        },
        {
            "md": 100.0,
            "inclination": 10.0,
            "azimuthTN": 38.52944953384463,
            "azimuthGN": 40.0,
            "dxTN": 5.422189533665295,
            "dyTN": 6.809439428156647,
            "point": {
                "x": 400005.59360307665,
                "y": 6500006.666196379,
                "z": 0.5069229954701058
            },
            "wgs84Longitude": 1.2779000901442394,
            "wgs84Latitude": 58.62883218086717,
            "dls": 3.048000000000004,
            "original": true,
            "dz": 99.4930770045299
        }
    ],
    "localCRS": "{\"name\":\"Azimuthal Equidistant\",\"type\":\"LBC\",\"ver\":\"PE_10_9_1\",\"wkt\":\"PROJCS[\\\"Azimuthal Equidistant Lng=1.27780675;Lat=58.62877105\\\",GEOGCS[\\\"GCS_WGS_1984\\\",DATUM[\\\"D_WGS_1984\\\",SPHEROID[\\\"WGS_1984\\\",6378137.0,298.257223563]],PRIMEM[\\\"Greenwich\\\",0.0],UNIT[\\\"Degree\\\",0.0174532925199433]],PROJECTION[\\\"Modified Azimuthal_Equidistant\\\"],PARAMETER[\\\"False_Easting\\\",0.0],PARAMETER[\\\"False_Northing\\\",0.0],PARAMETER[\\\"Central_Meridian\\\",1.2778067531835273],PARAMETER[\\\"Latitude_Of_Origin\\\",58.62877104865958],UNIT[\\\"Meter\\\",1.0]]\"}",
    "method": "AzimuthalEquidistant",
    "operationsApplied": [
        "derived TN from GN azimuth by grid convergence 358.529450",
        "unitMD Factor value: 1.0 is used for computation of MD",
        "computed deflections via minimum curvature method",
        "computation method: AzimuthalEquidistant",
        "conversion from 'Azimuthal Equidistant' to 'GCS_WGS_1984'",
        "conversion from 'GCS_WGS_1984' to 'WGS_1984_UTM_Zone_31N'",
        "to WGS 84: conversion from WGS_1984_UTM_Zone_31N to GCS_WGS_1984; 2 points converted",
        "Interpolation for MD_i input stations;2 points interpolated",
        "to WGS 84: conversion from WGS_1984_UTM_Zone_31N to GCS_WGS_1984; 2 points converted"
    ],
    "stations_i": [
        {
            "md": 50.0,
            "inclination": 4.999999999999992,
            "azimuthTN": 38.52944953384463,
            "azimuthGN": 40.0,
            "dxTN": 1.35813143348407,
            "dyTN": 1.7056050280731863,
            "point": {
                "x": 400001.40145529207,
                "y": 6500001.670189307,
                "z": 50.063437802312535
            },
            "wgs84Longitude": 1.2778301383620794,
            "wgs84Latitude": 58.628786365100225,
            "dls": 5.0,
            "original": false,
            "dz": 49.936562197687465
        },
        {
            "md": 75.0,
            "inclination": 7.4999999999999645,
            "azimuthTN": 38.52944953384463,
            "azimuthGN": 40.0,
            "dxTN": 3.0533721019185904,
            "dyTN": 3.834567613423716,
            "point": {
                "x": 400003.1507734719,
                "y": 6500003.754945532,
                "z": 25.214000698777227
            },
            "wgs84Longitude": 1.2778593281324027,
            "wgs84Latitude": 58.628805483313386,
            "dls": 7.499999999999999,
            "original": false,
            "dz": 74.78599930122277
        }
    ],
    "scaleConvergenceList": [
        {
            "scalefactor": 0.999723,
            "convergence": -1.47055,
            "point": {
                "x": 399999.99999999936,
                "y": 6499999.999999927,
                "z": 100.0
            }
        },
        {
            "scalefactor": 0.999723,
            "convergence": -1.47047,
            "point": {
                "x": 400005.59360307665,
                "y": 6500006.666196379,
                "z": 0.5069229954701058
            }
        }
    ],
    "unitMD": "{\"abcd\":{\"a\":0.0,\"b\":1.0,\"c\":1.0,\"d\":0.0},\"symbol\":\"m\",\"baseMeasurement\":{\"ancestry\":\"L\",\"type\":\"UM\"},\"type\":\"UAD\"}",
    "inputKind": "MD_Incl_Azim"
},
    "ScaleConvergence": {
      "type": "object",
      "properties": {
        "scalefactor": {
          "type": "number",
	  "description":"Multiplier to correct a distance along the ellipsoid (“geodetic distance”) to the grid plane of the map projection (“grid distance”). Note: only a conformal map projection has the same point scale factor in all directions at a given location",
	  "example":"0.999723",
          "format": "double"
        },
        "convergence": {
          "type": "number",
	  "description":"Grid convergence is important in wellbore positioning if azimuth angles are reported referenced to Grid North and observations need to be corrected. ",
	  "example":"-1.47055",
          "format": "double"
        },
        "point": {
          "$ref": "#/definitions/Point"
        }
      }
    }
  },
  "VersionInfo": {
    "type": "object",
    "properties": {
      "artifactId": {
        "type": "string"
      },
      "branch": {
        "type": "string"
      },
      "buildTime": {
        "type": "string"
      },
      "commitId": {
        "type": "string"
      },
      "commitMessage": {
        "type": "string"
      },
      "connectedOuterServices": {
        "type": "array"
      },
      "groupId": {
        "type": "string"
      },
      "version": {
        "type": "string"
      }
    }
  }
}